### ISSUE TITLE
Configurate Publishing Decisions and Tags

### ISSUE THREAD

**Issue by pdurancastro** [campusdomar/PuMuKIT2-doc#12]
Hi. I'm testing Pumukit v.2.3 on my computer with the example. 
In the admin mode I would like to change the Publishing Decisions but only "University" it's unlocked. Also I would like to know how to add another Publishing Decisions and linked them to the Categories in front-end like University category.
I have tried to change the publishing_decision_i18n.csv with the new categories but did'nt work.
I would be very grateful if you could help me and give me some information to edit the user interface.

**Comment by albacodina** [comment]
Hi!
1) If you want to add or edit a pub decision, you must click on Tables > Tags. You can see an option called PUBDECISIONS, you must click on "+" icon and add a new publishing decision or edit one already created clicking on "Pencil" icon. To show this pub decision on the video's publication tab you must clik on "Display" checkbox.
2) For the other question, you must edit the file 'https://github.com/campusdomar/PuMuKIT/blob/2.3.x/src/Pumukit/WebTVBundle/Resources/views/Index/categories.html.twig', add a new block but in the link you must write the following route:

`{{ path('pumukit_webtv_bytag_multimediaobjects', {'tagCod': yourNewTagCod}) }}`

If you have another question, just ask and we will help you.

**Comment by pdurancastro** [comment]
Thank you. I close de issue.
